name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          # Apt fix and update
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update || sudo apt-get update --fix-missing
          
          # Minimal essential tools
          sudo apt-get install -y --no-install-recommends \
            git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          
          pip install --upgrade pip
          pip install --upgrade Cython==0.29.33 wheel setuptools
          pip install buildozer

      - name: Build with Buildozer
        run: |
          # Buildozer initialization and build
          yes | buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Vajra-System-Update
          path: bin/*.apk
