name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Isse build fast hoga

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.33 buildozer setuptools

      - name: Install System Dependencies
        # Yahan humne error handling aur mirror fixing add kar di hai
        run: |
          sudo apt-get update -y || true
          sudo apt-get install -y --no-install-recommends \
            git zip unzip openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Build with Buildozer
        # Is step mein hum path setup aur binary configuration handle karenge
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
          # 2026 Node 24 Support
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Vajra-System-Update
          path: bin/*.apk
          if-no-files-found: error
          
